In [1]:
# Install dependencies
%pip install pandas matplotlib scikit-learn imbalanced-learn keras tensorflow --quiet

from features import get_train_test_data

data = get_train_test_data("data/bank_data_train.csv", sampler="none")

print(f"x_train shape: {data.x_train.shape}")
print(f"x_test shape: {data.x_test.shape}")
print(f"y_train shape: {data.y_train.shape}")
print(f"y_test shape: {data.y_test.shape}")

# Display first 5 rows of x_train
data.x_train.head()

/home/samy/churn/.venv/bin/python: No module named pip
Note: you may need to restart the kernel to use updated packages.
x_train shape: (284152, 44)
x_test shape: (71038, 44)
y_train shape: (284152,)
y_test shape: (71038,)

        CR_PROD_CNT_IL  TURNOVER_DYNAMIC_IL_1M  ...  PACK_M01  PACK_O01
54105         2.061893               -0.044935  ...       0.0       1.0
313302       -0.244365               -0.044935  ...       0.0       0.0
302648       -0.244365               -0.044935  ...       0.0       0.0
350887        2.061893               -0.044935  ...       0.0       0.0
41493        -0.244365               -0.044935  ...       0.0       0.0

[5 rows x 44 columns]

In [2]:
# print name of features used for training
print(f"Features used for training: {data.x_train.columns.tolist()}")

Features used for training: ['CR_PROD_CNT_IL', 'TURNOVER_DYNAMIC_IL_1M', 'REST_DYNAMIC_FDEP_1M', 'REST_DYNAMIC_SAVE_3M', 'CR_PROD_CNT_VCU', 'REST_AVG_CUR', 'CR_PROD_CNT_TOVR', 'CR_PROD_CNT_PIL', 'TURNOVER_CC', 'TURNOVER_PAYM', 'AGE', 'CR_PROD_CNT_CC', 'REST_DYNAMIC_FDEP_3M', 'REST_DYNAMIC_IL_1M', 'CR_PROD_CNT_CCFP', 'REST_DYNAMIC_CUR_1M', 'REST_AVG_PAYM', 'LDEAL_GRACE_DAYS_PCT_MED', 'REST_DYNAMIC_CUR_3M', 'TURNOVER_DYNAMIC_CUR_1M', 'REST_DYNAMIC_PAYM_3M', 'REST_DYNAMIC_IL_3M', 'TURNOVER_DYNAMIC_IL_3M', 'REST_DYNAMIC_PAYM_1M', 'TURNOVER_DYNAMIC_CUR_3M', 'CLNT_SETUP_TENOR', 'TURNOVER_DYNAMIC_PAYM_3M', 'TURNOVER_DYNAMIC_PAYM_1M', 'REST_DYNAMIC_CC_1M', 'TURNOVER_DYNAMIC_CC_1M', 'REST_DYNAMIC_CC_3M', 'TURNOVER_DYNAMIC_CC_3M', 'PACK_101', 'PACK_102', 'PACK_103', 'PACK_104', 'PACK_105', 'PACK_107', 'PACK_108', 'PACK_109', 'PACK_301', 'PACK_K01', 'PACK_M01', 'PACK_O01']

In [4]:
# keras neural network classifier
import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.optimizers import Adam

model = Sequential([
    Dense(512, activation='relu', input_dim=data.x_train.shape[1], kernel_regularizer=keras.regularizers.l2(1e-9)),
    Dropout(0.1),
    Dense(512, activation='relu', kernel_regularizer=keras.regularizers.l2(1e-9)),
    Dropout(0.1),
    Dense(1, activation='sigmoid', kernel_regularizer=keras.regularizers.l2(1e-9))
])

import keras
from keras.callbacks import Callback

class StopAtAUC(Callback):
    def __init__(self, target_auc=0.85, monitor='val_auc'):
        super().__init__()
        self.target_auc = target_auc
        self.monitor = monitor
    
    def on_epoch_end(self, _, logs=None):
        current_auc = logs.get(self.monitor)
        current_auc = float(current_auc) if current_auc is not None else None
        if current_auc is not None and current_auc >= self.target_auc:
            print(f"\n\nReached target AUC of {self.target_auc:.4f}! Stopping training.")
            self.model.stop_training = True

stop_at_auc = StopAtAUC(target_auc=0.85, monitor='auc')

LOSS_FUNCTION = 'binary_crossentropy'
LEARNING_RATE = 0.001
EPOCHS = 60
BATCH_SIZE = 1024

model.compile(loss=LOSS_FUNCTION, optimizer=Adam(learning_rate=LEARNING_RATE), metrics=[keras.metrics.AUC(name='auc')])

model.fit(data.x_train, data.y_train, epochs=EPOCHS, batch_size=BATCH_SIZE, callbacks=[stop_at_auc], verbose=1)

Epoch 1/60

/home/samy/churn/.venv/lib/python3.12/site-packages/keras/src/layers/core/dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

278/278 ━━━━━━━━━━━━━━━━━━━━ 8s 27ms/step - auc: 0.6963 - loss: 0.2691
Epoch 2/60
278/278 ━━━━━━━━━━━━━━━━━━━━ 8s 28ms/step - auc: 0.7636 - loss: 0.2474
Epoch 3/60
278/278 ━━━━━━━━━━━━━━━━━━━━ 5s 16ms/step - auc: 0.7802 - loss: 0.2423
Epoch 4/60
278/278 ━━━━━━━━━━━━━━━━━━━━ 8s 27ms/step - auc: 0.7901 - loss: 0.2392
Epoch 5/60
278/278 ━━━━━━━━━━━━━━━━━━━━ 8s 28ms/step - auc: 0.7957 - loss: 0.2372
Epoch 6/60
278/278 ━━━━━━━━━━━━━━━━━━━━ 10s 34ms/step - auc: 0.8022 - loss: 0.2350
Epoch 7/60
278/278 ━━━━━━━━━━━━━━━━━━━━ 7s 24ms/step - auc: 0.8064 - loss: 0.2335
Epoch 8/60
278/278 ━━━━━━━━━━━━━━━━━━━━ 9s 34ms/step - auc: 0.8094 - loss: 0.2323
Epoch 9/60
278/278 ━━━━━━━━━━━━━━━━━━━━ 10s 35ms/step - auc: 0.8123 - loss: 0.2312
Epoch 10/60
278/278 ━━━━━━━━━━━━━━━━━━━━ 6s 23ms/step - auc: 0.8141 - loss: 0.2304
Epoch 11/60
278/278 ━━━━━━━━━━━━━━━━━━━━ 9s 31ms/step - auc: 0.8171 - loss: 0.2293
Epoch 12/60
278/278 ━━━━━━━━━━━━━━━━━━━━ 9s 33ms/step - auc: 0.8188 - loss: 0.2286
Epoch 13/60
278/278 ━━━━━━━━━━━━━━━━━━━━ 7s 26ms/step - auc: 0.8209 - loss: 0.2278
Epoch 14/60
278/278 ━━━━━━━━━━━━━━━━━━━━ 9s 34ms/step - auc: 0.8226 - loss: 0.2271
Epoch 15/60
278/278 ━━━━━━━━━━━━━━━━━━━━ 9s 31ms/step - auc: 0.8234 - loss: 0.2267
Epoch 16/60
278/278 ━━━━━━━━━━━━━━━━━━━━ 6s 23ms/step - auc: 0.8261 - loss: 0.2255
Epoch 17/60
278/278 ━━━━━━━━━━━━━━━━━━━━ 9s 32ms/step - auc: 0.8262 - loss: 0.2254
Epoch 18/60
278/278 ━━━━━━━━━━━━━━━━━━━━ 9s 32ms/step - auc: 0.8281 - loss: 0.2247
Epoch 19/60
278/278 ━━━━━━━━━━━━━━━━━━━━ 9s 31ms/step - auc: 0.8287 - loss: 0.2244
Epoch 20/60
278/278 ━━━━━━━━━━━━━━━━━━━━ 6s 21ms/step - auc: 0.8311 - loss: 0.2233
Epoch 21/60
278/278 ━━━━━━━━━━━━━━━━━━━━ 9s 33ms/step - auc: 0.8324 - loss: 0.2226
Epoch 22/60
278/278 ━━━━━━━━━━━━━━━━━━━━ 9s 34ms/step - auc: 0.8323 - loss: 0.2227
Epoch 23/60
278/278 ━━━━━━━━━━━━━━━━━━━━ 6s 22ms/step - auc: 0.8341 - loss: 0.2219
Epoch 24/60
278/278 ━━━━━━━━━━━━━━━━━━━━ 9s 32ms/step - auc: 0.8356 - loss: 0.2212
Epoch 25/60
278/278 ━━━━━━━━━━━━━━━━━━━━ 9s 33ms/step - auc: 0.8379 - loss: 0.2202
Epoch 26/60
278/278 ━━━━━━━━━━━━━━━━━━━━ 6s 22ms/step - auc: 0.8383 - loss: 0.2199
Epoch 27/60
278/278 ━━━━━━━━━━━━━━━━━━━━ 9s 32ms/step - auc: 0.8390 - loss: 0.2195
Epoch 28/60
278/278 ━━━━━━━━━━━━━━━━━━━━ 9s 32ms/step - auc: 0.8396 - loss: 0.2190
Epoch 29/60
278/278 ━━━━━━━━━━━━━━━━━━━━ 9s 31ms/step - auc: 0.8410 - loss: 0.2183
Epoch 30/60
278/278 ━━━━━━━━━━━━━━━━━━━━ 6s 21ms/step - auc: 0.8427 - loss: 0.2175
Epoch 31/60
278/278 ━━━━━━━━━━━━━━━━━━━━ 9s 31ms/step - auc: 0.8437 - loss: 0.2171
Epoch 32/60
278/278 ━━━━━━━━━━━━━━━━━━━━ 9s 32ms/step - auc: 0.8439 - loss: 0.2168
Epoch 33/60
278/278 ━━━━━━━━━━━━━━━━━━━━ 6s 22ms/step - auc: 0.8456 - loss: 0.2159
Epoch 34/60
278/278 ━━━━━━━━━━━━━━━━━━━━ 7s 26ms/step - auc: 0.8470 - loss: 0.2151
Epoch 35/60
278/278 ━━━━━━━━━━━━━━━━━━━━ 7s 25ms/step - auc: 0.8481 - loss: 0.2145
Epoch 36/60
278/278 ━━━━━━━━━━━━━━━━━━━━ 7s 26ms/step - auc: 0.8485 - loss: 0.2144
Epoch 37/60
217/278 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - auc: 0.8555 - loss: 0.2117

Reached target AUC of 0.8500! Stopping training.
278/278 ━━━━━━━━━━━━━━━━━━━━ 4s 16ms/step - auc: 0.8501 - loss: 0.2134

In [4]:
LIBRARYNAME = "keras"
ALGORITHMNAME = "neural_network"

metrics = model.get_metrics_result()
AUC = metrics['auc']
LOSS = metrics['loss']

import pandas as pd

print(model.summary())

pd.DataFrame({
    'Library': [LIBRARYNAME],
    'Algorithm': [ALGORITHMNAME],
    'LossFunction': [LOSS_FUNCTION],
    'LearningRate': [LEARNING_RATE],
    'Epochs': [EPOCHS],
    'BatchSize': [BATCH_SIZE],
    'AUC': [AUC],
    'Loss': [LOSS]
})

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │         2,112 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 64)             │         4,160 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 19,013 (74.27 KB)

 Trainable params: 6,337 (24.75 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 12,676 (49.52 KB)

None

,Library,Algorithm,LossFunction,LearningRate,Epochs,BatchSize,AUC,Loss
0,keras,neural_network,binary_crossentropy,0.001,300,1024,0.849541,0.213481

In [6]:
from features import get_test_data

selected_features = data.x_train.columns.tolist()
df = get_test_data("data/bank_data_test.csv", data)
test_df = df[selected_features]

predictions = model.predict(test_df)
predictions

2775/2775 ━━━━━━━━━━━━━━━━━━━━ 4s 1ms/step

array([[0.17869318],
       [0.00529136],
       [0.01792705],
       ...,
       [0.0342129 ],
       [0.00266396],
       [0.41390225]], shape=(88798, 1), dtype=float32)

In [8]:
# save probabilities to csv file with ID and TARGET column
import pandas as pd

output_df = pd.DataFrame({
    'ID': df['ID'],
    'TARGET': predictions.flatten()
})
output_df.to_csv("churn_keras_predictions.csv", index=False)
output_df.head()

       ID    TARGET
0  400980  0.178693
1  525062  0.005291
2  280316  0.017927
3  496066  0.024806
4  375031  0.000932