In [1]:
# Install dependencies (add imbalanced-learn)
%pip install pandas matplotlib scikit-learn imbalanced-learn --quiet

from features import get_train_test_data

data = get_train_test_data("data/bank_data_train.csv")

print(f"x_train shape: {data.x_train.shape}")
print(f"x_test shape: {data.x_test.shape}")
print(f"y_train shape: {data.y_train.shape}")
print(f"y_test shape: {data.y_test.shape}")

# Display first 5 rows of x_train
data.x_train.head()

/home/samy/churn/.venv/bin/python: No module named pip
Note: you may need to restart the kernel to use updated packages.
x_train shape: (284152, 44)
x_test shape: (71038, 44)
y_train shape: (284152,)
y_test shape: (71038,)

        CR_PROD_CNT_IL  TURNOVER_DYNAMIC_IL_1M  ...  PACK_M01  PACK_O01
54105         2.061893               -0.044935  ...       0.0       1.0
313302       -0.244365               -0.044935  ...       0.0       0.0
302648       -0.244365               -0.044935  ...       0.0       0.0
350887        2.061893               -0.044935  ...       0.0       0.0
41493        -0.244365               -0.044935  ...       0.0       0.0

[5 rows x 44 columns]

In [2]:
# print name of features used for training
print(f"Features used for training: {data.x_train.columns.tolist()}")

Features used for training: ['CR_PROD_CNT_IL', 'TURNOVER_DYNAMIC_IL_1M', 'REST_DYNAMIC_FDEP_1M', 'REST_DYNAMIC_SAVE_3M', 'CR_PROD_CNT_VCU', 'REST_AVG_CUR', 'CR_PROD_CNT_TOVR', 'CR_PROD_CNT_PIL', 'TURNOVER_CC', 'TURNOVER_PAYM', 'AGE', 'CR_PROD_CNT_CC', 'REST_DYNAMIC_FDEP_3M', 'REST_DYNAMIC_IL_1M', 'CR_PROD_CNT_CCFP', 'REST_DYNAMIC_CUR_1M', 'REST_AVG_PAYM', 'LDEAL_GRACE_DAYS_PCT_MED', 'REST_DYNAMIC_CUR_3M', 'TURNOVER_DYNAMIC_CUR_1M', 'REST_DYNAMIC_PAYM_3M', 'REST_DYNAMIC_IL_3M', 'TURNOVER_DYNAMIC_IL_3M', 'REST_DYNAMIC_PAYM_1M', 'TURNOVER_DYNAMIC_CUR_3M', 'CLNT_SETUP_TENOR', 'TURNOVER_DYNAMIC_PAYM_3M', 'TURNOVER_DYNAMIC_PAYM_1M', 'REST_DYNAMIC_CC_1M', 'TURNOVER_DYNAMIC_CC_1M', 'REST_DYNAMIC_CC_3M', 'TURNOVER_DYNAMIC_CC_3M', 'PACK_101', 'PACK_102', 'PACK_103', 'PACK_104', 'PACK_105', 'PACK_107', 'PACK_108', 'PACK_109', 'PACK_301', 'PACK_K01', 'PACK_M01', 'PACK_O01']

In [ ]:
from sklearn.dummy import DummyClassifier
from sklearn.metrics import roc_auc_score, accuracy_score

# Train Naive Bayes
naive_clf = DummyClassifier(strategy='most_frequent')
naive_clf.fit(data.x_train, data.y_train)

# Predict probabilities
y_pred = naive_clf.predict(data.x_test)
y_proba = naive_clf.predict_proba(data.x_test)[:, 1]

# Calculate AUC
acc = accuracy_score(data.y_test, y_pred)
auc = roc_auc_score(data.y_test, y_proba)

print(f"AUC: {auc:.4f}")
print(f"Accuracy: {acc:.4f}")

AUC: 0.5000
Accuracy: 0.9186

In [4]:
# print classification report
from sklearn.metrics import classification_report
print(classification_report(data.y_test, y_pred))

              precision    recall  f1-score   support

           0       0.92      1.00      0.96     65253
           1       0.00      0.00      0.00      5785

    accuracy                           0.92     71038
   macro avg       0.46      0.50      0.48     71038
weighted avg       0.84      0.92      0.88     71038

/home/samy/churn/.venv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/home/samy/churn/.venv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/home/samy/churn/.venv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [5]:
import pandas as pd

LIBRARY_NAME = "scikit-learn"
ALORITHM = "GaussianNB"


# get model summary
print("Model Summary:")
model_summary = {
    "library": LIBRARY_NAME,
    "algorithm": ALORITHM,
    "auc": auc,
    "accuracy": acc,
}
model_summary_df = pd.DataFrame([model_summary])
model_summary_df.T

Model Summary:

                      0
library    scikit-learn
algorithm    GaussianNB
auc                 0.5
accuracy       0.918565