In [1]:
# Install dependencies (add imbalanced-learn)
%pip install pandas matplotlib scikit-learn imbalanced-learn keras tensorflow --quiet

from features import get_train_test_data

x_train, x_test, y_train, y_test = get_train_test_data("data/bank_data_train.csv")

print(f"x_train shape: {x_train.shape}")
print(f"x_test shape: {x_test.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"y_test shape: {y_test.shape}")

# Display first 5 rows of x_train
x_train.head()

/home/samy/churn/.venv/bin/python: No module named pip
Note: you may need to restart the kernel to use updated packages.
x_train shape: (284152, 32)
x_test shape: (71038, 32)
y_train shape: (284152,)
y_test shape: (71038,)

,CR_PROD_CNT_IL,TURNOVER_DYNAMIC_IL_1M,REST_DYNAMIC_FDEP_1M,REST_DYNAMIC_SAVE_3M,CR_PROD_CNT_VCU,REST_AVG_CUR,CR_PROD_CNT_TOVR,CR_PROD_CNT_PIL,TURNOVER_CC,TURNOVER_PAYM,AGE,CR_PROD_CNT_CC,REST_DYNAMIC_FDEP_3M,REST_DYNAMIC_IL_1M,CR_PROD_CNT_CCFP,REST_DYNAMIC_CUR_1M,REST_AVG_PAYM,LDEAL_GRACE_DAYS_PCT_MED,REST_DYNAMIC_CUR_3M,TURNOVER_DYNAMIC_CUR_1M,REST_DYNAMIC_PAYM_3M,REST_DYNAMIC_IL_3M,TURNOVER_DYNAMIC_IL_3M,REST_DYNAMIC_PAYM_1M,TURNOVER_DYNAMIC_CUR_3M,CLNT_SETUP_TENOR,TURNOVER_DYNAMIC_PAYM_3M,TURNOVER_DYNAMIC_PAYM_1M,REST_DYNAMIC_CC_1M,TURNOVER_DYNAMIC_CC_1M,REST_DYNAMIC_CC_3M,TURNOVER_DYNAMIC_CC_3M
0,2.061893,-0.044935,-0.052273,-0.312231,5.244695,-0.110851,1.176112,-0.192559,-0.038441,-0.093385,-0.976263,-0.242002,-0.086736,-0.068473,-0.064618,0.258930,-0.151018,-0.045033,0.283547,0.190178,-0.375206,-0.099585,-0.075343,-0.284607,0.326273,-0.610612,-0.347538,-0.24017,-0.083058,-0.031616,-0.108653,-0.07104
1,-0.244365,-0.044935,-0.052273,2.151389,-0.169621,0.192015,-0.526426,-0.192559,-0.038441,-0.093385,-1.064184,-0.242002,-0.086736,-0.068473,-0.064618,-0.286218,-0.151018,-0.045033,-0.227630,0.140643,-0.375206,-0.099585,-0.075343,-0.284607,-0.316017,1.144931,-0.347538,-0.24017,-0.083058,-0.031616,-0.108653,-0.07104
2,-0.244365,-0.044935,-0.052273,-0.312231,-0.169621,-0.260938,-0.526426,-0.192559,-0.038441,-0.093385,1.837201,-0.242002,-0.086736,-0.068473,-0.064618,-0.433742,-0.151018,-0.045033,-0.448334,-0.392441,-0.375206,-0.099585,-0.075343,-0.284607,-0.661855,-1.081618,-0.347538,-0.24017,-0.083058,-0.031616,-0.108653,-0.07104
3,2.061893,-0.044935,-0.052273,-0.312231,-0.169621,-0.332548,1.176112,-0.192559,-0.038441,-0.093385,-0.184976,-0.242002,-0.086736,-0.068473,-0.064618,0.039323,-0.151018,-0.045033,0.836577,0.003751,-0.375206,-0.099585,-0.075343,-0.284607,0.899380,-0.425565,-0.347538,-0.24017,-0.083058,-0.031616,-0.108653,-0.07104
4,-0.244365,-0.044935,-0.052273,-0.312231,-0.169621,-0.291020,1.176112,-0.192559,-0.038441,-0.093385,-1.327946,-0.242002,-0.086736,-0.068473,-0.064618,0.799208,-0.151018,-0.045033,1.675035,1.528313,-0.375206,-0.099585,-0.075343,-0.284607,1.554690,-0.719649,-0.347538,-0.24017,-0.083058,-0.031616,-0.108653,-0.07104

In [2]:
# print name of features used for training
print(f"Features used for training: {x_train.columns.tolist()}")

Features used for training: ['CR_PROD_CNT_IL', 'TURNOVER_DYNAMIC_IL_1M', 'REST_DYNAMIC_FDEP_1M', 'REST_DYNAMIC_SAVE_3M', 'CR_PROD_CNT_VCU', 'REST_AVG_CUR', 'CR_PROD_CNT_TOVR', 'CR_PROD_CNT_PIL', 'TURNOVER_CC', 'TURNOVER_PAYM', 'AGE', 'CR_PROD_CNT_CC', 'REST_DYNAMIC_FDEP_3M', 'REST_DYNAMIC_IL_1M', 'CR_PROD_CNT_CCFP', 'REST_DYNAMIC_CUR_1M', 'REST_AVG_PAYM', 'LDEAL_GRACE_DAYS_PCT_MED', 'REST_DYNAMIC_CUR_3M', 'TURNOVER_DYNAMIC_CUR_1M', 'REST_DYNAMIC_PAYM_3M', 'REST_DYNAMIC_IL_3M', 'TURNOVER_DYNAMIC_IL_3M', 'REST_DYNAMIC_PAYM_1M', 'TURNOVER_DYNAMIC_CUR_3M', 'CLNT_SETUP_TENOR', 'TURNOVER_DYNAMIC_PAYM_3M', 'TURNOVER_DYNAMIC_PAYM_1M', 'REST_DYNAMIC_CC_1M', 'TURNOVER_DYNAMIC_CC_1M', 'REST_DYNAMIC_CC_3M', 'TURNOVER_DYNAMIC_CC_3M']

In [ ]:
import tensorflow as tf

LIBRARYNAME = "TensorFlow"
ALGORITHMNAME = "Feedforward Neural Network"
LOSS_FUNCTION = "binary_crossentropy"
LEARNING_RATE = 0.001
EPOCHS = 100
BATCH_SIZE = 1024

# Define model architecture
# def create_model(input_dim):
#     # Input layer
#     inputs = tf.keras.Input(shape=(input_dim,))
    
#     # Hidden layers
#     x = tf.keras.layers.Dense(64, activation='relu')(inputs)
#     x = tf.keras.layers.Dense(64, activation='relu')(x)
    
#     # Output layer
#     outputs = tf.keras.layers.Dense(1, activation='sigmoid')(x)
    
#     return tf.keras.Model(inputs=inputs, outputs=outputs)

from tensorflow.keras import regularizers

def create_model(input_dim, dropout_rate=0.2, l2_reg=1e-39):
    inputs = tf.keras.Input(shape=(input_dim,))



        # Hidden layer 1
    x = tf.keras.layers.Dense(512, activation='relu',
                               kernel_regularizer=regularizers.l2(l2_reg))(inputs)
    x = tf.keras.layers.Dropout(dropout_rate)(x)

    # Hidden layer 2
    x = tf.keras.layers.Dense(512, activation='relu',
                               kernel_regularizer=regularizers.l2(l2_reg))(x)
    x = tf.keras.layers.Dropout(dropout_rate)(x)

    # Output layer
    outputs = tf.keras.layers.Dense(1, activation='sigmoid',
                                    kernel_regularizer=regularizers.l2(l2_reg))(x)

    return tf.keras.Model(inputs=inputs, outputs=outputs)

model = create_model(x_train.shape[1])

# Compile model
model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=LEARNING_RATE),
    loss=LOSS_FUNCTION,
    metrics=[tf.keras.metrics.AUC(name='auc')]
)

# Custom callback to stop at target AUC
class StopAtTargetAUC(tf.keras.callbacks.Callback):
    def __init__(self, target_auc=0.85):
        super().__init__()
        self.target_auc = target_auc
    
    def on_epoch_end(self, _, logs=None):
        val_auc = logs.get('auc')
        if val_auc is not None:
            val_auc = float(val_auc)
            if val_auc >= self.target_auc:
                print(f"\nReached target AUC of {self.target_auc}! Stopping training.")
                self.model.stop_training = True

# Train model
history = model.fit(
    x_train,
    y_train,
    epochs=EPOCHS,
    batch_size=BATCH_SIZE,
    callbacks=[StopAtTargetAUC(target_auc=0.85)],
    verbose=1
)

Epoch 1/160
278/278 ━━━━━━━━━━━━━━━━━━━━ 8s 25ms/step - auc: 0.6863 - loss: 0.2715
Epoch 2/160
278/278 ━━━━━━━━━━━━━━━━━━━━ 7s 25ms/step - auc: 0.7544 - loss: 0.2501
Epoch 3/160
278/278 ━━━━━━━━━━━━━━━━━━━━ 7s 24ms/step - auc: 0.7718 - loss: 0.2451
Epoch 4/160
278/278 ━━━━━━━━━━━━━━━━━━━━ 4s 15ms/step - auc: 0.7824 - loss: 0.2418
Epoch 5/160
278/278 ━━━━━━━━━━━━━━━━━━━━ 7s 24ms/step - auc: 0.7888 - loss: 0.2397
Epoch 6/160
278/278 ━━━━━━━━━━━━━━━━━━━━ 8s 29ms/step - auc: 0.7946 - loss: 0.2378
Epoch 7/160
278/278 ━━━━━━━━━━━━━━━━━━━━ 8s 28ms/step - auc: 0.7978 - loss: 0.2365
Epoch 8/160
278/278 ━━━━━━━━━━━━━━━━━━━━ 4s 15ms/step - auc: 0.8023 - loss: 0.2350
Epoch 9/160
278/278 ━━━━━━━━━━━━━━━━━━━━ 7s 25ms/step - auc: 0.8059 - loss: 0.2337
Epoch 10/160
278/278 ━━━━━━━━━━━━━━━━━━━━ 7s 26ms/step - auc: 0.8079 - loss: 0.2331
Epoch 11/160
278/278 ━━━━━━━━━━━━━━━━━━━━ 7s 24ms/step - auc: 0.8099 - loss: 0.2324
Epoch 12/160
278/278 ━━━━━━━━━━━━━━━━━━━━ 7s 24ms/step - auc: 0.8104 - loss: 0.2319
Epoch 13/160
278/278 ━━━━━━━━━━━━━━━━━━━━ 4s 15ms/step - auc: 0.8131 - loss: 0.2311
Epoch 14/160
278/278 ━━━━━━━━━━━━━━━━━━━━ 7s 24ms/step - auc: 0.8134 - loss: 0.2309
Epoch 15/160
278/278 ━━━━━━━━━━━━━━━━━━━━ 7s 24ms/step - auc: 0.8149 - loss: 0.2304
Epoch 16/160
278/278 ━━━━━━━━━━━━━━━━━━━━ 7s 26ms/step - auc: 0.8160 - loss: 0.2300
Epoch 17/160
278/278 ━━━━━━━━━━━━━━━━━━━━ 5s 16ms/step - auc: 0.8165 - loss: 0.2298
Epoch 18/160
278/278 ━━━━━━━━━━━━━━━━━━━━ 8s 28ms/step - auc: 0.8181 - loss: 0.2291
Epoch 19/160
278/278 ━━━━━━━━━━━━━━━━━━━━ 7s 27ms/step - auc: 0.8184 - loss: 0.2289
Epoch 20/160
278/278 ━━━━━━━━━━━━━━━━━━━━ 7s 27ms/step - auc: 0.8193 - loss: 0.2286
Epoch 21/160
278/278 ━━━━━━━━━━━━━━━━━━━━ 5s 19ms/step - auc: 0.8195 - loss: 0.2285
Epoch 22/160
278/278 ━━━━━━━━━━━━━━━━━━━━ 8s 28ms/step - auc: 0.8205 - loss: 0.2281
Epoch 23/160
278/278 ━━━━━━━━━━━━━━━━━━━━ 8s 28ms/step - auc: 0.8215 - loss: 0.2276
Epoch 24/160
278/278 ━━━━━━━━━━━━━━━━━━━━ 7s 27ms/step - auc: 0.8216 - loss: 0.2276
Epoch 25/160
278/278 ━━━━━━━━━━━━━━━━━━━━ 4s 15ms/step - auc: 0.8227 - loss: 0.2270
Epoch 26/160
278/278 ━━━━━━━━━━━━━━━━━━━━ 7s 26ms/step - auc: 0.8236 - loss: 0.2268
Epoch 27/160
278/278 ━━━━━━━━━━━━━━━━━━━━ 7s 24ms/step - auc: 0.8240 - loss: 0.2265
Epoch 28/160
278/278 ━━━━━━━━━━━━━━━━━━━━ 7s 24ms/step - auc: 0.8252 - loss: 0.2261
Epoch 29/160
278/278 ━━━━━━━━━━━━━━━━━━━━ 4s 14ms/step - auc: 0.8255 - loss: 0.2259
Epoch 30/160
278/278 ━━━━━━━━━━━━━━━━━━━━ 7s 24ms/step - auc: 0.8257 - loss: 0.2257
Epoch 31/160
278/278 ━━━━━━━━━━━━━━━━━━━━ 7s 25ms/step - auc: 0.8265 - loss: 0.2253
Epoch 32/160
278/278 ━━━━━━━━━━━━━━━━━━━━ 7s 23ms/step - auc: 0.8264 - loss: 0.2253
Epoch 33/160
278/278 ━━━━━━━━━━━━━━━━━━━━ 7s 26ms/step - auc: 0.8273 - loss: 0.2250
Epoch 34/160
278/278 ━━━━━━━━━━━━━━━━━━━━ 6s 20ms/step - auc: 0.8276 - loss: 0.2247
Epoch 35/160
278/278 ━━━━━━━━━━━━━━━━━━━━ 8s 27ms/step - auc: 0.8288 - loss: 0.2242
Epoch 36/160
278/278 ━━━━━━━━━━━━━━━━━━━━ 7s 25ms/step - auc: 0.8292 - loss: 0.2240
Epoch 37/160
278/278 ━━━━━━━━━━━━━━━━━━━━ 7s 24ms/step - auc: 0.8294 - loss: 0.2239
Epoch 38/160
278/278 ━━━━━━━━━━━━━━━━━━━━ 4s 15ms/step - auc: 0.8300 - loss: 0.2236
Epoch 39/160
278/278 ━━━━━━━━━━━━━━━━━━━━ 7s 25ms/step - auc: 0.8316 - loss: 0.2232
Epoch 40/160
278/278 ━━━━━━━━━━━━━━━━━━━━ 7s 26ms/step - auc: 0.8311 - loss: 0.2231
Epoch 41/160
278/278 ━━━━━━━━━━━━━━━━━━━━ 7s 25ms/step - auc: 0.8319 - loss: 0.2226
Epoch 42/160
278/278 ━━━━━━━━━━━━━━━━━━━━ 4s 15ms/step - auc: 0.8324 - loss: 0.2225
Epoch 43/160
278/278 ━━━━━━━━━━━━━━━━━━━━ 7s 25ms/step - auc: 0.8331 - loss: 0.2222
Epoch 44/160
278/278 ━━━━━━━━━━━━━━━━━━━━ 7s 24ms/step - auc: 0.8333 - loss: 0.2221
Epoch 45/160
278/278 ━━━━━━━━━━━━━━━━━━━━ 7s 25ms/step - auc: 0.8340 - loss: 0.2216
Epoch 46/160
278/278 ━━━━━━━━━━━━━━━━━━━━ 4s 15ms/step - auc: 0.8352 - loss: 0.2211
Epoch 47/160
278/278 ━━━━━━━━━━━━━━━━━━━━ 7s 25ms/step - auc: 0.8353 - loss: 0.2211
Epoch 48/160
278/278 ━━━━━━━━━━━━━━━━━━━━ 7s 24ms/step - auc: 0.8354 - loss: 0.2210
Epoch 49/160
278/278 ━━━━━━━━━━━━━━━━━━━━ 7s 24ms/step - auc: 0.8364 - loss: 0.2206
Epoch 50/160
278/278 ━━━━━━━━━━━━━━━━━━━━ 7s 25ms/step - auc: 0.8367 - loss: 0.2203
Epoch 51/160
278/278 ━━━━━━━━━━━━━━━━━━━━ 4s 14ms/step - auc: 0.8375 - loss: 0.2199
Epoch 52/160
278/278 ━━━━━━━━━━━━━━━━━━━━ 7s 25ms/step - auc: 0.8378 - loss: 0.2199
Epoch 53/160
278/278 ━━━━━━━━━━━━━━━━━━━━ 7s 26ms/step - auc: 0.8385 - loss: 0.2195
Epoch 54/160
278/278 ━━━━━━━━━━━━━━━━━━━━ 7s 25ms/step - auc: 0.8384 - loss: 0.2196
Epoch 55/160
278/278 ━━━━━━━━━━━━━━━━━━━━ 4s 14ms/step - auc: 0.8391 - loss: 0.2190
Epoch 56/160
278/278 ━━━━━━━━━━━━━━━━━━━━ 7s 25ms/step - auc: 0.8398 - loss: 0.2188
Epoch 57/160
278/278 ━━━━━━━━━━━━━━━━━━━━ 7s 26ms/step - auc: 0.8398 - loss: 0.2187
Epoch 58/160
278/278 ━━━━━━━━━━━━━━━━━━━━ 7s 24ms/step - auc: 0.8407 - loss: 0.2182
Epoch 59/160
278/278 ━━━━━━━━━━━━━━━━━━━━ 4s 15ms/step - auc: 0.8412 - loss: 0.2180
Epoch 60/160
278/278 ━━━━━━━━━━━━━━━━━━━━ 7s 25ms/step - auc: 0.8414 - loss: 0.2178
Epoch 61/160
278/278 ━━━━━━━━━━━━━━━━━━━━ 7s 24ms/step - auc: 0.8424 - loss: 0.2175
Epoch 62/160
278/278 ━━━━━━━━━━━━━━━━━━━━ 7s 25ms/step - auc: 0.8429 - loss: 0.2170
Epoch 63/160
278/278 ━━━━━━━━━━━━━━━━━━━━ 8s 27ms/step - auc: 0.8427 - loss: 0.2173
Epoch 64/160
278/278 ━━━━━━━━━━━━━━━━━━━━ 5s 17ms/step - auc: 0.8432 - loss: 0.2170
Epoch 65/160
278/278 ━━━━━━━━━━━━━━━━━━━━ 7s 26ms/step - auc: 0.8447 - loss: 0.2163
Epoch 66/160
278/278 ━━━━━━━━━━━━━━━━━━━━ 7s 26ms/step - auc: 0.8452 - loss: 0.2160
Epoch 67/160
278/278 ━━━━━━━━━━━━━━━━━━━━ 8s 28ms/step - auc: 0.8451 - loss: 0.2161
Epoch 68/160
278/278 ━━━━━━━━━━━━━━━━━━━━ 5s 17ms/step - auc: 0.8456 - loss: 0.2156
Epoch 69/160
278/278 ━━━━━━━━━━━━━━━━━━━━ 7s 26ms/step - auc: 0.8456 - loss: 0.2156
Epoch 70/160
278/278 ━━━━━━━━━━━━━━━━━━━━ 7s 25ms/step - auc: 0.8464 - loss: 0.2151
Epoch 71/160
278/278 ━━━━━━━━━━━━━━━━━━━━ 7s 25ms/step - auc: 0.8465 - loss: 0.2150
Epoch 72/160
278/278 ━━━━━━━━━━━━━━━━━━━━ 4s 14ms/step - auc: 0.8476 - loss: 0.2145
Epoch 73/160
278/278 ━━━━━━━━━━━━━━━━━━━━ 7s 26ms/step - auc: 0.8475 - loss: 0.2144
Epoch 74/160
278/278 ━━━━━━━━━━━━━━━━━━━━ 7s 24ms/step - auc: 0.8487 - loss: 0.2139
Epoch 75/160
278/278 ━━━━━━━━━━━━━━━━━━━━ 7s 24ms/step - auc: 0.8497 - loss: 0.2134
Epoch 76/160
278/278 ━━━━━━━━━━━━━━━━━━━━ 4s 15ms/step - auc: 0.8489 - loss: 0.2138
Epoch 77/160
278/278 ━━━━━━━━━━━━━━━━━━━━ 8s 27ms/step - auc: 0.8496 - loss: 0.2133
Epoch 78/160
276/278 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - auc: 0.8533 - loss: 0.2118
Reached target AUC of 0.85! Stopping training.
278/278 ━━━━━━━━━━━━━━━━━━━━ 8s 29ms/step - auc: 0.8506 - loss: 0.2128

In [ ]:
import pandas as pd

metrics = model.get_metrics_result()

LOSS = metrics["loss"]
AUC = metrics["auc"]

print(model.summary())

pd.DataFrame({
    'Library': [LIBRARYNAME],
    'Algorithm': [ALGORITHMNAME],
    'LossFunction': [LOSS_FUNCTION],
    'LearningRate': [LEARNING_RATE],
    'Epochs': [EPOCHS],
    'BatchSize': [BATCH_SIZE],
    'AUC': [AUC],
    'Loss': [LOSS]
}).T

Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)        │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 64)             │         2,112 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 64)             │         4,160 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 19,013 (74.27 KB)

 Trainable params: 6,337 (24.75 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 12,676 (49.52 KB)

None

                                       0
Library                       TensorFlow
Algorithm     Feedforward Neural Network
LossFunction         binary_crossentropy
LearningRate                       0.001
Epochs                               500
BatchSize                           1024
AUC                             0.850515
Loss                            0.213066